name: clang-format-check

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - name: Start container
      run: |
        docker run -it --name CI_container \
                   -v ${GITHUB_WORKSPACE}:/Package \
                   -v /cvmfs:/cvmfs:shared \
                   -p 80:80 \
                   -d ghcr.io/key4hep/key4hep-images/ubuntu22:latest \
                   /bin/bash
    - name: Run clang-format
      run: |
        docker exec CI_container /bin/bash -c 'cd Package; \
           source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh; \
           clang-format --dry-run --Werror src/* include/ral/*'
